"""
命令行工具 - Agent Bridge CLI
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Optional


def cmd_create(args):
    """创建新工具模板"""
    from .tool import Tool, ToolWrapper
    
    template_dir = Path(__file__).parent.parent / "templates"
    template_file = template_dir / f"{args.template}.py"
    
    if not template_file.exists():
        # 使用默认模板
        content = f'''"""
{args.name} - TODO: Add description

Generated by Agent Bridge
"""

from agent_bridge import Tool


@Tool(
    name="{args.name}",
    description="TODO: Add description",
    parameters={{
        # "param1": {{"type": "string", "required": True, "description": "Parameter description"}},
    }},
    tags=["{args.template}"],
)
def {args.name.replace("-", "_")}(**kwargs):
    """TODO: Implement this function"""
    pass


# Test
if __name__ == "__main__":
    result = {args.name.replace("-", "_")}()
    print(result)
'''
    else:
        content = template_file.read_text().replace("{{name}}", args.name)
    
    output_file = Path(args.output) if args.output else Path(f"{args.name}.py")
    output_file.write_text(content, encoding="utf-8")
    
    print(f"✅ Created: {output_file}")
    return 0


def cmd_convert(args):
    """转换工具格式"""
    from .converter import Converter
    
    source = Path(args.source)
    output = Path(args.output) if args.output else Path(f"./converted_{args.to_format}")
    
    if source.is_dir():
        # 批量转换
        converted = Converter.batch_convert(
            str(source),
            str(output),
            from_format=args.from_format,
            to_format=args.to_format,
        )
        print(f"✅ Converted {len(converted)} tools to {output}")
        for path in converted:
            print(f"   - {path}")
    else:
        # 单个文件转换
        print("❌ Directory source required for batch conversion")
        return 1
    
    return 0


def cmd_validate(args):
    """验证工具兼容性"""
    from .tool import ToolWrapper
    from .converter import Converter
    
    tool_path = Path(args.path)
    
    try:
        if (tool_path / "SKILL.md").exists():
            # OpenClaw skill
            tool = Converter.from_openclaw(str(tool_path))
            print(f"✅ Valid OpenClaw Skill: {tool.tool.name}")
        elif tool_path.suffix == ".py":
            # Hermes tool or standalone
            tool = Converter.from_hermes(str(tool_path))
            print(f"✅ Valid Hermes Tool: {tool.tool.name}")
        else:
            print(f"❌ Unknown format: {tool_path}")
            return 1
        
        # 验证元数据
        if not tool.tool.name:
            print("❌ Missing tool name")
            return 1
        
        if not tool.tool.description:
            print("⚠️  Missing description (recommended)")
        
        print(f"📋 Parameters: {len(tool.tool.parameters)}")
        print(f"🏷️  Tags: {tool.tool.tags}")
        
        return 0
    
    except Exception as e:
        print(f"❌ Validation failed: {e}")
        return 1


def cmd_publish(args):
    """发布工具"""
    from .converter import Converter
    
    tool_path = Path(args.path)
    platforms = args.platforms.split(",") if args.platforms else ["clawhub"]
    
    print(f"📦 Publishing to: {', '.join(platforms)}")
    
    # TODO: 实现实际发布逻辑
    for platform in platforms:
        if platform == "clawhub":
            print(f"   → ClawHub: Not yet implemented")
        elif platform == "hermes":
            print(f"   → Hermes Hub: Not yet implemented")
        else:
            print(f"   → {platform}: Unknown platform")
    
    return 0


def cmd_sync(args):
    """同步工具库"""
    from .openclaw import OpenClawAdapter
    from .hermes import HermesAdapter
    
    source = args.source
    dest = args.dest
    
    print(f"🔄 Syncing from {source} to {dest}")
    
    if source == "clawhub":
        adapter = OpenClawAdapter()
        skills = adapter.sync_from_clawhub(args.category)
        print(f"   Synced {len(skills)} skills")
    else:
        print(f"❌ Unknown source: {source}")
        return 1
    
    return 0


def cmd_list(args):
    """列出工具"""
    from .openclaw import OpenClawAdapter
    from .hermes import HermesAdapter
    
    if args.format == "openclaw":
        adapter = OpenClawAdapter()
        tools = adapter.list_skills()
    elif args.format == "hermes":
        adapter = HermesAdapter()
        tools = adapter.list_tools()
    else:
        print("❌ Unknown format. Use 'openclaw' or 'hermes'")
        return 1
    
    if not tools:
        print("📭 No tools found")
        return 0
    
    print(f"📦 Found {len(tools)} tools:\n")
    for tool in tools:
        print(f"  • {tool['name']}")
        print(f"    {tool['description'][:60]}..." if len(tool['description']) > 60 else f"    {tool['description']}")
        if tool.get('tags'):
            print(f"    Tags: {', '.join(tool['tags'])}")
        print()
    
    return 0


def cmd_run(args):
    """运行工具"""
    import subprocess
    
    tool_name = args.name
    tool_args = json.loads(args.args) if args.args else {}
    
    # 查找工具
    from .openclaw import OpenClawAdapter
    
    adapter = OpenClawAdapter()
    result = adapter.run_skill(tool_name, tool_args)
    
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


def main():
    """CLI 入口点"""
    parser = argparse.ArgumentParser(
        prog="agent-bridge",
        description="🌉 Agent Bridge - 让 OpenClaw 和 Hermes Agent 共享技能/工具",
    )
    
    subparsers = parser.add_subparsers(dest="command", help="Commands")
    
    # create 命令
    create_parser = subparsers.add_parser("create", help="创建新工具模板")
    create_parser.add_argument("name", help="工具名称")
    create_parser.add_argument("-t", "--template", default="general", help="模板类型")
    create_parser.add_argument("-o", "--output", help="输出文件路径")
    create_parser.set_defaults(func=cmd_create)
    
    # convert 命令
    convert_parser = subparsers.add_parser("convert", help="转换工具格式")
    convert_parser.add_argument("source", help="源目录")
    convert_parser.add_argument("--from", dest="from_format", required=True, help="源格式 (openclaw/hermes)")
    convert_parser.add_argument("--to", dest="to_format", required=True, help="目标格式 (openclaw/hermes)")
    convert_parser.add_argument("-o", "--output", help="输出目录")
    convert_parser.set_defaults(func=cmd_convert)
    
    # validate 命令
    validate_parser = subparsers.add_parser("validate", help="验证工具兼容性")
    validate_parser.add_argument("path", help="工具路径")
    validate_parser.set_defaults(func=cmd_validate)
    
    # publish 命令
    publish_parser = subparsers.add_parser("publish", help="发布工具")
    publish_parser.add_argument("path", help="工具路径")
    publish_parser.add_argument("-p", "--platforms", help="发布平台 (逗号分隔)")
    publish_parser.set_defaults(func=cmd_publish)
    
    # sync 命令
    sync_parser = subparsers.add_parser("sync", help="同步工具库")
    sync_parser.add_argument("--source", required=True, help="源 (clawhub/hermes)")
    sync_parser.add_argument("--dest", default="local", help="目标")
    sync_parser.add_argument("-c", "--category", help="分类过滤")
    sync_parser.set_defaults(func=cmd_sync)
    
    # list 命令
    list_parser = subparsers.add_parser("list", help="列出工具")
    list_parser.add_argument("-f", "--format", default="openclaw", help="工具格式")
    list_parser.set_defaults(func=cmd_list)
    
    # run 命令
    run_parser = subparsers.add_parser("run", help="运行工具")
    run_parser.add_argument("name", help="工具名称")
    run_parser.add_argument("-a", "--args", help="JSON 格式参数")
    run_parser.set_defaults(func=cmd_run)
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return 0
    
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
