"""
格式转换器 - OpenClaw 和 Hermes Agent 之间的工具格式转换
"""

import json
import os
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from .tool import Tool, ToolWrapper, ToolRegistry


class Converter:
    """格式转换器"""
    
    @staticmethod
    def to_openclaw(tool: Union[ToolWrapper, Dict], output_dir: Optional[str] = None) -> str:
        """
        转换为 OpenClaw Skill 格式
        
        OpenClaw Skill 结构:
        - SKILL.md (元数据)
        - scripts/ (脚本目录)
        - SKILL.md 包含 trigger, metadata 等
        """
        if isinstance(tool, ToolWrapper):
            tool_dict = tool.to_dict()
            func = tool.func
        else:
            tool_dict = tool
            func = None
        
        skill_name = tool_dict["name"].replace("-", "_")
        skill_dir = Path(output_dir) / skill_name if output_dir else Path(skill_name)
        skill_dir.mkdir(parents=True, exist_ok=True)
        
        # 创建 SKILL.md
        skill_md = f"""---
name: {tool_dict["name"]}
description: {tool_dict["description"]}
author: {tool_dict.get("author", "agent-bridge")}
version: {tool_dict.get("version", "1.0.0")}
triggers:
  - "{tool_dict["name"]}"
  - "{tool_dict["description"].split()[0] if tool_dict["description"] else tool_dict["name"]}"
metadata: {{"category": "{tool_dict.get("category", "general")}", "tags": {json.dumps(tool_dict.get("tags", []))}}}
---

# {tool_dict["name"].replace("-", " ").title()}

{tool_dict["description"]}

## Usage

```bash
# CLI 用法
agent-bridge run {tool_dict["name"]} [arguments]

# Python 用法
from agent_bridge import {skill_name}
result = {skill_name}(**args)
```

## Parameters

{Converter._format_params_md(tool_dict.get("parameters", {}))}

## Examples

```python
# 示例代码
result = {skill_name}()
print(result)
```

---

*Generated by Agent Bridge*
"""
        
        (skill_dir / "SKILL.md").write_text(skill_md, encoding="utf-8")
        
        # 创建 scripts 目录和 Python 脚本
        scripts_dir = skill_dir / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        
        if func:
            # 生成可执行的 Python 脚本
            script_content = Converter._generate_python_script(tool_dict, func)
            (scripts_dir / f"{skill_name}.py").write_text(script_content, encoding="utf-8")
        
        # 创建 README
        readme = f"""# {tool_dict["name"].replace("-", " ").title()}

{tool_dict["description"]}

## Installation

```bash
# 作为 OpenClaw Skill 安装
cp -r {skill_name} ~/.openclaw/workspace/skills/
```

## Usage

```bash
# 通过 OpenClaw 调用
openclaw run {tool_dict["name"]} [args]
```

## License

MIT
"""
        (skill_dir / "README.md").write_text(readme, encoding="utf-8")
        
        return str(skill_dir)
    
    @staticmethod
    def to_hermes(tool: Union[ToolWrapper, Dict], output_dir: Optional[str] = None) -> str:
        """
        转换为 Hermes Agent 工具格式
        
        Hermes 工具结构:
        - tools/
          - {tool_name}.py (工具实现)
          - __init__.py (注册)
        """
        if isinstance(tool, ToolWrapper):
            tool_dict = tool.to_dict()
            func = tool.func
        else:
            tool_dict = tool
            func = None
        
        tool_name = tool_dict["name"].replace("-", "_")
        tool_dir = Path(output_dir) / "tools" if output_dir else Path("tools")
        tool_dir.mkdir(parents=True, exist_ok=True)
        
        # 生成 Hermes 工具文件
        hermes_content = f'''"""
{tool_dict["name"]} - {tool_dict["description"]}

Generated by Agent Bridge
"""

from typing import Any, Dict, Optional
from hermes.tools.base import BaseTool


class {tool_name.title().replace("_", "")}Tool(BaseTool):
    """{tool_dict["description"]}"""
    
    name = "{tool_dict["name"]}"
    description = """{tool_dict["description"]}"""
    
    parameters = {{
{Converter._format_hermes_params(tool_dict.get("parameters", {}))}
    }}
    
    def _run(self, **kwargs) -> Any:
        """执行工具"""
        # TODO: 实现具体逻辑
{Converter._generate_hermes_run_body(tool_dict.get("parameters", {}))}
        pass
    
    async def _arun(self, **kwargs) -> Any:
        """异步执行"""
        return await asyncio.to_thread(self._run, **kwargs)


# 导出工具实例
tool = {tool_name.title().replace("_", "")}Tool()
'''
        
        (tool_dir / f"{tool_name}.py").write_text(hermes_content, encoding="utf-8")
        
        # 更新或创建 __init__.py
        init_file = tool_dir / "__init__.py"
        if init_file.exists():
            content = init_file.read_text(encoding="utf-8")
            if tool_name not in content:
                content += f"\nfrom .{tool_name} import tool as {tool_name}"
                init_file.write_text(content, encoding="utf-8")
        else:
            init_content = f'''"""
Hermes Agent Tools - Generated by Agent Bridge
"""

from .{tool_name} import tool as {tool_name}

__all__ = ["{tool_name}"]
'''
            init_file.write_text(init_content, encoding="utf-8")
        
        return str(tool_dir)
    
    @staticmethod
    def from_openclaw(skill_path: str) -> ToolWrapper:
        """从 OpenClaw Skill 加载"""
        skill_path = Path(skill_path)
        skill_md = skill_path / "SKILL.md"
        
        if not skill_md.exists():
            raise ValueError(f"Not a valid OpenClaw skill: {skill_path}")
        
        # 解析 SKILL.md 头部 YAML
        content = skill_md.read_text(encoding="utf-8")
        metadata = Converter._parse_skill_header(content)
        
        # 创建 ToolWrapper
        tool = Tool(
            name=metadata.get("name", skill_path.name),
            description=metadata.get("description", ""),
            author=metadata.get("author", ""),
            version=metadata.get("version", "1.0.0"),
            tags=metadata.get("metadata", {}).get("tags", []),
            category=metadata.get("metadata", {}).get("category", "general"),
        )
        
        # 创建占位函数
        def placeholder(**kwargs):
            raise NotImplementedError("Tool implementation not available")
        
        wrapper = ToolWrapper(placeholder, tool)
        return wrapper
    
    @staticmethod
    def from_hermes(tool_path: str) -> ToolWrapper:
        """从 Hermes 工具加载"""
        tool_path = Path(tool_path)
        
        if not tool_path.exists():
            raise ValueError(f"Tool file not found: {tool_path}")
        
        # 解析 Python 文件提取元数据
        content = tool_path.read_text(encoding="utf-8")
        metadata = Converter._parse_hermes_tool(content)
        
        tool = Tool(
            name=metadata.get("name", tool_path.stem),
            description=metadata.get("description", ""),
            parameters=metadata.get("parameters", {}),
        )
        
        def placeholder(**kwargs):
            raise NotImplementedError("Tool implementation not available")
        
        wrapper = ToolWrapper(placeholder, tool)
        return wrapper
    
    @staticmethod
    def batch_convert(
        source_dir: str,
        target_dir: str,
        from_format: str,
        to_format: str,
    ) -> List[str]:
        """批量转换"""
        source_path = Path(source_dir)
        target_path = Path(target_dir)
        target_path.mkdir(parents=True, exist_ok=True)
        
        converted = []
        
        if from_format == "openclaw":
            # 遍历所有技能目录
            for skill_dir in source_path.iterdir():
                if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
                    try:
                        tool = Converter.from_openclaw(str(skill_dir))
                        if to_format == "hermes":
                            result = Converter.to_hermes(tool, str(target_path))
                        else:
                            result = Converter.to_openclaw(tool, str(target_path))
                        converted.append(result)
                    except Exception as e:
                        print(f"Failed to convert {skill_dir.name}: {e}")
        
        elif from_format == "hermes":
            tools_dir = source_path / "tools"
            if tools_dir.exists():
                for tool_file in tools_dir.glob("*.py"):
                    if tool_file.name != "__init__.py":
                        try:
                            tool = Converter.from_hermes(str(tool_file))
                            if to_format == "openclaw":
                                result = Converter.to_openclaw(tool, str(target_path))
                            else:
                                result = Converter.to_hermes(tool, str(target_path))
                            converted.append(result)
                        except Exception as e:
                            print(f"Failed to convert {tool_file.name}: {e}")
        
        return converted
    
    # ========== 辅助方法 ==========
    
    @staticmethod
    def _format_params_md(params: Dict) -> str:
        """格式化参数为 Markdown"""
        if not params:
            return "No parameters"
        
        lines = []
        for name, schema in params.items():
            req = "required" if schema.get("required", True) else "optional"
            ptype = schema.get("type", "string")
            desc = schema.get("description", "")
            default = schema.get("default")
            
            line = f"- **{name}** ({ptype}, {req})"
            if desc:
                line += f": {desc}"
            if default is not None:
                line += f" (default: `{default}`)"
            lines.append(line)
        
        return "\n".join(lines)
    
    @staticmethod
    def _format_hermes_params(params: Dict) -> str:
        """格式化参数为 Hermes 格式"""
        if not params:
            return "        # No parameters"
        
        lines = []
        for name, schema in params.items():
            ptype = schema.get("type", "string")
            req = schema.get("required", True)
            desc = schema.get("description", "")
            
            hermes_type = {
                "string": "str",
                "integer": "int",
                "number": "float",
                "boolean": "bool",
                "array": "list",
                "object": "dict",
            }.get(ptype, "Any")
            
            default = "" if req else f" = None"
            lines.append(f'        "{name}": {{"type": "{hermes_type}", "description": "{desc}"}}{default},')
        
        return "\n".join(lines)
    
    @staticmethod
    def _generate_hermes_run_body(params: Dict) -> str:
        """生成 Hermes _run 方法体"""
        if not params:
            return "        # Extract parameters\n"
        
        lines = ["        # Extract parameters"]
        for name in params.keys():
            lines.append(f'        {name} = kwargs.get("{name}")')
        
        return "\n".join(lines)
    
    @staticmethod
    def _generate_python_script(tool_dict: Dict, func) -> str:
        """生成 Python 脚本"""
        # 尝试获取函数源码
        try:
            source = inspect.getsource(func)
        except (TypeError, OSError):
            source = "# TODO: Implement tool logic\npass"
        
        return f'''#!/usr/bin/env python3
"""
{tool_dict["name"]} - {tool_dict["description"]}

Generated by Agent Bridge
"""

import sys
import json

{source}

def main():
    """CLI entry point"""
    if len(sys.argv) < 2:
        print(json.dumps({{"error": "No arguments provided"}}))
        sys.exit(1)
    
    # 解析参数
    try:
        args = json.loads(sys.argv[1]) if sys.argv[1].startswith("{{") else {{"query": sys.argv[1]}}
    except json.JSONDecodeError:
        args = {{"query": " ".join(sys.argv[1:])}}
    
    # 执行
    try:
        result = {tool_dict["name"].replace("-", "_")}(**args)
        print(json.dumps({{"success": True, "result": result}}, ensure_ascii=False))
    except Exception as e:
        print(json.dumps({{"success": False, "error": str(e)}}))
        sys.exit(1)

if __name__ == "__main__":
    main()
'''
    
    @staticmethod
    def _parse_skill_header(content: str) -> Dict:
        """解析 SKILL.md 头部 YAML"""
        import re
        
        # 提取 YAML 部分
        match = re.search(r"^---\n(.*?)\n---", content, re.DOTALL)
        if not match:
            return {}
        
        yaml_content = match.group(1)
        metadata = {}
        
        # 简单 YAML 解析
        for line in yaml_content.split("\n"):
            if ":" in line:
                key, value = line.split(":", 1)
                key = key.strip()
                value = value.strip()
                
                # 处理列表
                if value.startswith("[") or value.startswith("-"):
                    # 简单处理列表
                    metadata[key] = []
                # 处理嵌套字典
                elif value.startswith("{"):
                    import ast
                    try:
                        metadata[key] = ast.literal_eval(value)
                    except:
                        metadata[key] = value
                else:
                    metadata[key] = value.strip('"\'')
        
        return metadata
    
    @staticmethod
    def _parse_hermes_tool(content: str) -> Dict:
        """解析 Hermes 工具文件"""
        import re
        
        metadata = {}
        
        # 提取 name
        name_match = re.search(r'name\s*=\s*["\']([^"\']+)["\']', content)
        if name_match:
            metadata["name"] = name_match.group(1)
        
        # 提取 description
        desc_match = re.search(r'description\s*=\s*["\']{3}(.+?)["\']{3}', content, re.DOTALL)
        if desc_match:
            metadata["description"] = desc_match.group(1).strip()
        
        # 提取 parameters
        params_match = re.search(r'parameters\s*=\s*\{(.+?)\}', content, re.DOTALL)
        if params_match:
            # 简化处理，实际需要更复杂的解析
            metadata["parameters"] = {}
        
        return metadata


# 快捷函数
def convert_to_openclaw(tool: Union[ToolWrapper, Dict], output_dir: Optional[str] = None) -> str:
    """转换为 OpenClaw 格式"""
    return Converter.to_openclaw(tool, output_dir)


def convert_to_hermes(tool: Union[ToolWrapper, Dict], output_dir: Optional[str] = None) -> str:
    """转换为 Hermes 格式"""
    return Converter.to_hermes(tool, output_dir)
