"""
Hermes Agent 适配器 - 与 Hermes Agent 工具系统集成
"""

import os
import json
import importlib
from pathlib import Path
from typing import Any, Dict, List, Optional

from .tool import Tool, ToolWrapper, ToolRegistry


class HermesAdapter:
    """Hermes Agent 适配器"""
    
    def __init__(self, tools_dir: Optional[str] = None):
        """
        初始化适配器
        
        Args:
            tools_dir: Hermes 工具目录
        """
        if tools_dir:
            self.tools_dir = Path(tools_dir)
        else:
            self.tools_dir = Path.cwd() / "tools"
        
        self.tools_dir.mkdir(parents=True, exist_ok=True)
    
    def install_tool(self, tool: Union[ToolWrapper, Dict], name: Optional[str] = None) -> str:
        """
        安装工具到 Hermes
        
        Args:
            tool: 工具定义
            name: 工具名称（可选）
        
        Returns:
            安装路径
        """
        from .converter import Converter
        
        tool_path = Converter.to_hermes(tool, str(self.tools_dir))
        return tool_path
    
    def load_tool(self, tool_name: str) -> Optional[Any]:
        """加载已安装的工具"""
        tool_file = self.tools_dir / f"{tool_name.replace('-', '_')}.py"
        
        if not tool_file.exists():
            return None
        
        # 动态导入
        spec = importlib.util.spec_from_file_location(tool_name, str(tool_file))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        return getattr(module, "tool", None)
    
    def list_tools(self) -> List[Dict]:
        """列出所有已安装的工具"""
        from .converter import Converter
        
        tools = []
        
        for tool_file in self.tools_dir.glob("*.py"):
            if tool_file.name == "__init__.py":
                continue
            
            try:
                tool = Converter.from_hermes(str(tool_file))
                tools.append(tool.to_dict())
            except Exception:
                continue
        
        return tools
    
    def register_to_agent(self, agent: Any, tool_names: Optional[List[str]] = None) -> int:
        """
        注册工具到 Hermes Agent
        
        Args:
            agent: Hermes Agent 实例
            tool_names: 要注册的工具名称列表，None 表示全部
        
        Returns:
            注册的工具数量
        """
        count = 0
        
        for tool_file in self.tools_dir.glob("*.py"):
            if tool_file.name == "__init__.py":
                continue
            
            if tool_names and tool_file.stem not in tool_names:
                continue
            
            tool = self.load_tool(tool_file.stem)
            if tool:
                agent.add_tool(tool)
                count += 1
        
        return count
    
    def get_tool_template(self, category: str = "general") -> str:
        """获取工具模板"""
        return f'''"""
My Tool - Description of what this tool does

Generated by Agent Bridge
"""

from typing import Any, Dict
from hermes.tools.base import BaseTool


class MyTool(BaseTool):
    """Tool description"""
    
    name = "my_tool"
    description = """Describe what this tool does"""
    
    parameters = {{
        "param1": {{"type": "str", "description": "Parameter description"}},
    }}
    
    def _run(self, **kwargs) -> Any:
        """Execute the tool"""
        param1 = kwargs.get("param1")
        
        # TODO: Implement your logic here
        result = {{}}
        
        return result
    
    async def _arun(self, **kwargs) -> Any:
        """Async execution"""
        import asyncio
        return await asyncio.to_thread(self._run, **kwargs)


# Export tool instance
tool = MyTool()
'''


# 需要导入 Union
from typing import Union
