"""
OpenClaw 适配器 - 与 OpenClaw Skills 系统集成
"""

import os
import json
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

from .tool import Tool, ToolWrapper, ToolRegistry


class OpenClawAdapter:
    """OpenClaw 适配器"""
    
    def __init__(self, workspace_dir: Optional[str] = None):
        """
        初始化适配器
        
        Args:
            workspace_dir: OpenClaw 工作目录，默认为 ~/.openclaw/workspace
        """
        if workspace_dir:
            self.workspace = Path(workspace_dir)
        else:
            self.workspace = Path.home() / ".openclaw" / "workspace"
        
        self.skills_dir = self.workspace / "skills"
        self.skills_dir.mkdir(parents=True, exist_ok=True)
    
    def install_skill(self, tool: Union[ToolWrapper, Dict], name: Optional[str] = None) -> str:
        """
        安装技能到 OpenClaw
        
        Args:
            tool: 工具定义
            name: 技能名称（可选）
        
        Returns:
            安装路径
        """
        from .converter import Converter
        
        skill_path = Converter.to_openclaw(tool, str(self.skills_dir))
        return skill_path
    
    def load_skill(self, skill_name: str) -> Optional[ToolWrapper]:
        """加载已安装的技能"""
        from .converter import Converter
        
        skill_path = self.skills_dir / skill_name
        if not skill_path.exists():
            return None
        
        return Converter.from_openclaw(str(skill_path))
    
    def list_skills(self) -> List[Dict]:
        """列出所有已安装的技能"""
        skills = []
        
        for skill_dir in self.skills_dir.iterdir():
            if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
                try:
                    tool = self.load_skill(skill_dir.name)
                    if tool:
                        skills.append(tool.to_dict())
                except Exception:
                    continue
        
        return skills
    
    def run_skill(self, skill_name: str, args: Dict) -> Any:
        """运行技能"""
        skill_path = self.skills_dir / skill_name / "scripts" / f"{skill_name.replace('-', '_')}.py"
        
        if not skill_path.exists():
            raise FileNotFoundError(f"Skill script not found: {skill_path}")
        
        # 执行 Python 脚本
        result = subprocess.run(
            ["python3", str(skill_path), json.dumps(args)],
            capture_output=True,
            text=True,
            cwd=str(skill_path.parent),
        )
        
        if result.returncode != 0:
            raise RuntimeError(f"Skill execution failed: {result.stderr}")
        
        return json.loads(result.stdout)
    
    def sync_from_clawhub(self, category: Optional[str] = None) -> List[str]:
        """从 ClawHub 同步技能"""
        # TODO: 实现 ClawHub API 调用
        print("ClawHub sync not yet implemented")
        return []
    
    def get_skill_template(self, category: str = "general") -> str:
        """获取技能模板"""
        return f"""---
name: my_skill
description: My awesome skill
author: Your Name
version: 1.0.0
triggers:
  - "my_skill"
  - "do something"
metadata: {{"category": "{category}", "tags": []}}
---

# My Skill

Description of what this skill does.

## Usage

```bash
uv run scripts/my_skill.py [arguments]
```

## Parameters

- **param1** (string, required): Description

## Examples

```python
result = my_skill(param1="value")
```

---

*Generated by Agent Bridge*
"""


# 需要导入 Union
from typing import Union
